# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

language:
  - cpp

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    packages:
      - gfortran

matrix:
  include:
    - os: linux
    - os: osx

install:
  # Info about OS
  - uname -a

  # Install GCC and gfortran
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install gcc; fi

script:
  - which gfortran

# https://docs.travis-ci.com/user/customizing-the-build/#Whitelisting-or-blacklisting-branches
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - /^pr\..*/
